version: '3.9'

services:
  backend-app:
    container_name: backend-app
    image: backend_app
    ports:
      - 8000:8000
    command: wait-for-it db:5432 -- /bin/sh -c 
             "./manage.py collectstatic --no-input &&
             ./manage.py migrate &&
             uwsgi --master --http :8000 --module core.project.wsgi"
    env_file:
      - ../.env
    links:
      - db